[package]
name = "space_shooter"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.amethyst]
version = "0.12"
default-features = false
features = ["vulkan", "audio"]

[dependencies]
rand = "0.6.5"
